### ISSUE TITLE
Is it possible to get readline running in this?

### ISSUE THREAD

**Issue by shanness** [EnigmaCurry/jython-shell-server#2]
Hi there,
if I try to import readline, I get this.
```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/craig/projects/ubookr-modules/lib/jython-standalone-2.7.0.jar/Lib/readline.py", line 9, in <module>
    raise ImportError("Cannot access JLine2 setup")
ImportError: Cannot access JLine2 setup
```
Anyhow, thanks very much for this project, if I can get readline working, it'll be very useful for us to do support work cleaning up data etc.

**Comment by EnigmaCurry** [comment]
I can't remember if I got readline to work or not, but I remember it was not out of the box. That was a decade ago though, things have probably changed a lot. I wonder if it would work if you tried the jython 2.5 release jar? It seems that version uses Jline (not Jline2.) I haven't used any of this in forever, so good luck! :game_die:

**Comment by shanness** [comment]
Thanks for getting back to me so fast, will check it out

**Comment by shanness** [comment]
Changed to jython-standalone-2.5.4-rc1.jar

And get this :- 

```
>>> import readline
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/craig/projects/ubookr-modules/lib/jython-standalone-2.5.4-rc1.jar/Lib/readline.py", line 20, in <module>
    raise ImportError("Cannot access JLineConsole")
ImportError: Cannot access JLineConsole
```

But running on that jar directly
```
java -jar jython-standalone-2.5.4-rc1.jar 
Jython 2.5.4rc1 (2.5:723492dbab02, Feb 8 2013, 10:13:55) 
[Java HotSpot(TM) 64-Bit Server VM (Oracle Corporation)] on java1.8.0_65
Type "help", "copyright", "credits" or "license" for more information.
>>> import readline
>>>
```
works, and had readline working already (without the import)..

So no idea what's wrong..  Maybe it's because we don't have a terminal?

**Comment by EnigmaCurry** [comment]
Try this https://stackoverflow.com/a/9809574/56560

**Comment by EnigmaCurry** [comment]
https://github.com/hanslub42/rlwrap

**Comment by oskar-skog** [comment]
I've had the same ImportError with different software on Jython.

Jython has an `-i` option that seems to fix this ImportError.
Use `jython -i program_that_uses_readline` instead of `jython program_that_uses_readline`.
